### ISSUE TITLE
Use shortCode on frontend

### ISSUE THREAD

**Issue by giuseppecapasso** [hasanuzzamanbe/wp-boilerplate-vue-with-vite#1]
Hi, I used the `registerShortCodes()` function to register a new shortcode to be used for rendering a component on the frontend.
But how do I use it? Where are the scripts imported to render a vue component on the frontend?

```
public function registerShortCodes() : void {
    add_shortcode('test_shortcode', static fn () => '<div id="app"></div>');
}
```

**Comment by shamim0902** [comment]
Hi @giuseppecapasso 
This app is only enqueued for the backend admin panel.
Using a different Vue app is better if you want to use it as a front-end application.
Just create a new application and enqueue the build file it when you want to render.

Please check the "/includes/LoadAssets.php" file if you want to use this app somewhere else just enqueue like this.

**Comment by giuseppecapasso** [comment]
Hi @hasanuzzamanbe,
thanks for the tip, I used the same system to add the missing scripts and render the app also on the frontend side.
Good job.

**Comment by smartosc-kienvm** [comment]
I'm create new app for frontend, it's work on local but not work when upload to server
