### ISSUE TITLE
Errors in console: 3 missing methods in WPPluginVueTailwind.js - dateTimeFormat, localDate, waitingTime

### ISSUE THREAD

**Issue by camya** [hasanuzzamanbe/wp-boilerplate-vue-with-vite#4]
Hi,
thank you for your great boilerplate. Really useful.

It looks like you've removed 3 methods in `WPPluginVueTailwind.js` while refactoring. Guess, it was to remove the momentJS dependency. Maybe it should be replaced with dayJs?

**Now the console shows some errors.** The `extendVueConstructor()` method now **misses the 3 methods** `self.dateTimeFormat`, `self.localDate`, and `self.waitingTime`.

**Comment by camya** [comment]
Hm, looks like these methods are never used anywhere in the code. Maybe they should just be removed from the app.mixin in extendVueConstructor?

```
// longLocalDate: self.longLocalDate,
// longLocalDateTime: self.longLocalDateTime,
// dateTimeFormat: self.dateTimeFormat,
// localDate: self.localDate,
// $waitingTime: self.waitingTime,
```

**Comment by shamim0902** [comment]
Thanks, @camya for letting me know, I will remove those dependencies.
